theme: jekyll-theme-minimal
title: Computer Science + Crop Sciences at the University of Illinois, Urbana-Champaign
description: Students in the CS+CPSC major may use this website to showcase their accomplishments and network with potential employers.
